/*======================================================================

   Space Game for the Nintendo DS by Steven S.
   December 2023
   Asteroid coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef ASTROID__H
#define ASTROID__H


#define ASTROID_BITMAP_WIDTH   32//128 //32 //128
#define ASTROID_BITMAP_HEIGHT   32//256 //192
#define ASTROID_NUM_IMAGES   8//10


		//	Format:
		//	U,V,Width,Height



const unsigned int astroid_texcoords[] = {
 0, 0, 32, 32,				// 0
 0, 32, 32, 32,				// 1
 0, 64, 32, 32,				// 2
 0, 96, 32, 32,				// 3
 0, 128, 32, 32,			// 4
 0, 160, 32, 32,			// 5
 0, 192, 32, 32,			// 6
 0, 224, 32, 32,			// 7
};


#endif
